config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get 'secret', to: 'pages#secret', as: :secret
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username, uniqueness: true

  acts_as_token_authenticatable

  devise :trackable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  acts_as_token_authentication_handler_for User, only: [:secret]

  def home
  end

  def secret
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lockr
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if notice
      %p.notice= notice
    - if alert
      %p.alert= alert
    = yield

app/views/pages/home.html.haml
%h1 Home
= link_to 'Secret', secret_path

app/views/pages/secret.html.haml
%h1 Secret
= link_to 'Home', root_path